[project]
name = "jisui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.20.0",
    "ollama-ocr>=0.1.6",
    "pdf2image>=1.17.0",
    "pillow>=11.2.1",
    "pypdf>=5.6.0",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.1.0",
    "transformers>=4.52.4",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
